AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  RoleExecuteLambda:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ParamProjectName}-execute-lambda-${ParamENV}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: !Sub ${ParamProjectName}-invoke-lambda-${ParamENV}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: [ "lambda:InvokeFunction" ]
                Resource: "*"

  FunctionCheck:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ParamProjectName}-check-${ParamENV}
      Runtime: go1.x
      Timeout: 180
      Handler: dist/check
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "states:DescribeExecution"
              Resource: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:execution:${MachineWorker.Name}:*"

  FunctionFan:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ParamProjectName}-fan-${ParamENV}
      Runtime: go1.x
      Timeout: 180
      Handler: dist/fan
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "states:StartExecution"
              Resource: !Ref MachineWorker
      Environment:
        Variables:
          MachineWorker: !Ref MachineWorker

  FunctionProcess:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ParamProjectName}-process-${ParamENV}
      Runtime: go1.x
      Timeout: 180
      Handler: dist/process
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableURL

  MachinePuppeteer:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub ${ParamProjectName}-puppeteer-${ParamENV}
      DefinitionString: !Sub |-
        {
            "Comment": "Process objects in DynamoDB",
            "StartAt": "Initialize",
            "States": {
              "Initialize": {
                "Type": "Choice",
                "Comment": "Check if Configuration is passed",
                "Choices": [
                  { 
                    "Variable": "$.Configuration.TableName",
                    "StringEquals": "",
                    "Next": "InvalidConfiguration"
                  },
                  { 
                    "Variable": "$.Configuration.TableHash",
                    "StringEquals": "",
                    "Next": "InvalidConfiguration"
                  },
                  { 
                    "Variable": "$.Configuration.Workers",
                    "NumericLessThan": 1,
                    "Next": "InvalidConfiguration"
                  },
                  { 
                    "Variable": "$.Configuration.BatchSize",
                    "NumericLessThan": 1,
                    "Next": "InvalidConfiguration"
                  }
                ],
                "Default": "Scale"
              },
              "Scale": {
                "Type": "Task",
                "Comment": "Start Machine Execution(s)",
                "Resource": "${FunctionFan.Arn}",
                "ResultPath": "$.ExecutionList",
                "Next": "Status"
              },
              "Status": {
                "Type": "Task",
                "Comment": "Get Status for Execution(s)",
                "Resource": "${FunctionCheck.Arn}",
                "ResultPath": "$.ExecutionList",
                "Next": "CheckAllDone"
              },
              "CheckAllDone": {
                "Type": "Choice",
                "Comment": "Check if all Workers are finished",
                "Choices": [
                  { 
                    "Variable": "$.ExecutionList.Status",
                    "StringEquals": "SUCCEEDED",
                    "Next": "Done"
                  }
                ],
                "Default": "Wait"
              },
              "Wait": {
                "Type": "Wait",
                "Seconds": 2,
                "Next": "Status"
              },
              "InvalidConfiguration": {
                "Type": "Fail",
                "Cause": "Invalid Configuration for Execution!",
                "Error": "InvalidConfiguration"
              },
              "Done": {
                "Type": "Pass",
                "End": true
              }
            }
        }
      RoleArn: !GetAtt RoleExecuteLambda.Arn

  MachineWorker:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub ${ParamProjectName}-worker-${ParamENV}
      DefinitionString: !Sub |-
        {
            "Comment": "State Machine",
            "StartAt": "Execute",
            "States": {
              "Execute": {
                "Type": "Task",
                "Comment": "Run process Lambda function",
                "Resource": "${FunctionProcess.Arn}",
                "ResultPath": "$.Iterator",
                "Next": "Check"
              },
              "Check": {
                "Type": "Choice",
                "Comment": "Check if DynamoDB contains more objects for processing",
                "Choices": [
                  { 
                    "Not": {
                      "Variable": "$.Iterator.Cursor",
                      "StringEquals": ""
                    },
                    "Next": "Execute"
                  }
                ],
                "Default": "Done"
              },
              "Done": {
                "Type": "Pass",
                "End": true
              }
            }
        }
      RoleArn: !GetAtt RoleExecuteLambda.Arn

  TableURL:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ParamProjectName}-url-${ParamENV}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: url
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S

Parameters:
  ParamProjectName:
    Type: String
  ParamENV:
    Type: String

Outputs:
  Puppeteer:
    Description: ARN for Puppeteer State Machine
    Value: !Ref MachinePuppeteer
